config/routes.rb
Webboard::Application.routes.draw do
  resources :users do
    resources :boards
  end
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/test',    to: 'test#test',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',   to: 'static_pages#about',   via: 'get'

end

app/models/board.rb
class Board < ActiveRecord::Base
	belongs_to :user
  validates :title, presence: true, length: { maximum: 40 }
	validates :user_id, presence: true
end

app/controllers/boards_controller.rb
##
# Class for controlling all the boards

class BoardsController < ApplicationController
  require 'json'
  respond_to :json

  ##
  # Lists all the boards belonging the the user (which is found by looking up the parameter id)
  def index
    redirect_to User.find(params[:user_id])
  end

  ##
  # Updates the contents of board.content by receiving ajax POST requests from board/show
  def update
    @user = User.find(params[:user_id])
    @board = @user.boards.find(params[:id])
    @board.update_column(:content, params[:board].as_json)
    respond_to do |format|
      format.json { render json: @board }
    end
  end

  ##
  # Creates a board with a provided title for the board, if it is saved correctly, "Board created!"
  # is flashed, otherwise (if the title length is above 40), the error gets flashed
  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      flash[:success] = "Board created!"
      redirect_to [@current_user, @board]
    else
      error = ''
      @board.errors.full_messages.each do |m|
        error += m
      end
      flash[:danger] = error
      redirect_to @current_user
    end
  end

  ##
  # Displays the main canvas page where the board is to be editted, if the current logged in user
  # isn't the owner of the board that is trying to be accessed, the current user gets redirected to
  # the user's (who's board was to be accessed) show page
  def show
    @user = User.find(params[:user_id])
    if current_user?(@user)
      @board = @user.boards.find(params[:id])
      @content = @board.content
      if @content
        @content = @board.content.gsub('\\', '').gsub(/.$/, '').gsub(/^./, '')
      end
    else
      flash[:danger] = 'Access denied'
      redirect_to @user
    end
  end

  private

    def board_params
      params.require(:board).permit(:title)
    end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
  <% if current_user?(@user) %>
    <%= link_to [@user, board], class: 'list-group-item' do%>
      <span class="list-user">
        <%= board.title %>
      </span>
      <span class="badge">Created <%= time_ago_in_words(board.created_at) %> ago</span>
    <% end %>
  <% else %>
    <li class="list-group-item">
      <span class="list-user">
        <%= board.title %>
      </span>
      <span class="badge">
        Created <%= time_ago_in_words(board.created_at) %> ago
      </span>
    </li>
  <% end %>

app/views/boards/_new.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= form_for([@user, @user.boards.build]) do |f| %>
        <div class="new-board-form">
            <%= f.text_field :title, placeholder: "Title of the board", :class => "form-control", :autofocus => true, :required => true %>
        </div>
        <%= f.submit "Create new board", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/boards/show.erb
<% provide(:title, @board.title) %>

<body>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<%= javascript_include_tag 'paperjs/paper-full.min.js' %>
<%= javascript_include_tag 'spectrum.js' %>

<h3 class="center"><%= @board.title %></h3>

<div class="row">
  <div class="canvas-heading">
    <div class="toolbar-item">
        <input type="text" class="toolbar-item" id="color-change" />
    </div>
    <input type="button" id="clear-canvas" class="btn btn-danger toolbar-item" value="Clear" data-placement="top" data-content="Not saved automatically">
  </div>
</div>
<div class="row">
  <div class="canvas-panel" style="overflow: auto;">
    <div class="canvas-body">
      <canvas id="board-canvas" width="1200" height="700"></canvas>
    </div>
  </div>
</div>

<input type="button" id="save-board" value="Save" class="btn btn-primary">

<script>
    function load() {
        project.importJSON(jQuery.parseJSON(("<%=j @content %>").replace(/&quot;/g, '"')));
    };

    function save() {
        var hash = project.exportJSON();
        var path = "<%=j user_board_url %>";
        $.ajax({
            type: "PUT",
            url: path,
            data: {board: JSON.stringify(hash)},
            dataType: 'json',
            success: function() { alert("Successfuly saved"); },
            error: function(status, error) {
                $("#debug").append($(status.responseText));
            }
        });
    };

    $("#save-board").click(function() {
        save();
    });

    $("#color-change").spectrum({
        change: function(c) {
            changeColor(c);
        }
    });

    $(function() {
        $( "#slider" ).slider({ min: 1, max: 20});
    });

    $("#clear-canvas").click(function() {
       clearCanvas();
    });

    $("#clear-canvas").popover();

    $("body").click(function(e) {
        if(!$("#clear-canvas").is(e.target)){
            $("#clear-canvas").popover("hide");
        }
    });
</script>

<div id="debug">

</div>

<%= javascript_include_tag 'toolbar.js' %>
<%= javascript_include_tag 'board.js' %>
</body>