config/routes.rb
Webboard::Application.routes.draw do
  resources :users do
    resources :boards
  end
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/test',    to: 'test#test',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',   to: 'static_pages#about',   via: 'get'

end

app/views/layouts/_navbar.html.erb
<div class="container">
	<div class="row">
		<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse" >
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="collapse">
              <%= link_to 'webboard', root_path, id: 'navbar-logo' %>
				<ul class="nav navbar-nav pull-right">
						<% if signed_in? %>
							<li id="account-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Account <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to "Profile", current_user %></li>
									<li><%= link_to "Settings", edit_user_path(current_user) %></li>
									<li class="divider"></li>
									<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
								</ul>
							</li>
						<% else %>
							<li><%= link_to "Sign up", signup_path %></li>
						<% end %>
            <li><%= link_to "All Users", users_path %></li>
						<li><%= link_to "About", about_path %></li>
            <li><%= link_to "Help", help_path %></li>
        </ul>
			</div>
		</nav>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title(yield(:title)) %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class="container">
		<% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
		<%= yield %>
    <!-- <%#= debug(params) if Rails.env.development? %> -->
	</div>
</body>
</html>